import Link from "next/link";
import type { Metadata } from "next";
import { IconArrowRight, IconHistory, IconQrcode, IconTool, IconTruckDelivery } from "@tabler/icons-react";
import { InlineCta, MarketingFooter, MarketingHeader, ProductWorkspace, WorkflowSteps } from "../../components/marketing";

export const metadata: Metadata = { title: "Construction Tool Tracking Features | TakeMoveReturn", description: "See the QR, TAKE, MOVE, RETURN, history, and field workflow features built for small construction crews.", alternates: { canonical: "/features" }, openGraph: { title: "Construction Tool Tracking Features | TakeMoveReturn", description: "See the QR, TAKE, MOVE, RETURN, history, and field workflow features built for small construction crews.", type: "website" } };

const features = [{ icon: IconQrcode, title: "QR labels that work in a browser", text: "Scan a tool label from a phone browser. Field work does not need a native app." }, { icon: IconTool, title: "TAKE, MOVE, RETURN", text: "Record the handoff that matters, then see the current holder and location." }, { icon: IconHistory, title: "Reliable history", text: "Movement, damage, maintenance, and corrections belong in the tool record." }, { icon: IconTruckDelivery, title: "Made for construction flow", text: "Follow reusable tools between workers, trucks, warehouses, and job sites." }];

export default function FeaturesPage() {
  return <main className="marketing-page"><MarketingHeader /><section className="page-hero"><p className="eyebrow">PRODUCT FEATURES</p><h1>Construction tool tracking without the busywork.</h1><p>One clear workflow for crews that need to know who has every tool and what happened to it.</p><Link className="button" href="/signup">Start free <IconArrowRight size={18} aria-hidden="true" /></Link></section><section className="feature-grid">{features.map(({ icon: Icon, title, text }) => <article key={title}><Icon size={34} stroke={1.8} aria-hidden="true" /><h2>{title}</h2><p>{text}</p></article>)}</section><section className="split-section"><div><p className="eyebrow">PRODUCT PREVIEW</p><h2>Built around the information your crew needs in the moment.</h2><p>Current holder, location, condition, and a readable history stay together in one tool record.</p></div><ProductWorkspace compact /></section><section className="section-heading"><p className="eyebrow">THE FIELD WORKFLOW</p><h2>Get from list to first scan without a complicated rollout.</h2></section><WorkflowSteps /><InlineCta /><MarketingFooter /></main>;
}
